from .base import BasePostProcessor, PostConfig
from .. import _core


class ABBRapidPostProcessor(BasePostProcessor):
    brand = "abb"
    controller = "irc5"

    def __init__(self):
        super().__init__(PostConfig(precision=3, speed_unit="mm/s", comment_char="!"))

    def _convert_wp(self, wp):
        if wp.type == _core.MoveType.JOINT:
            return {
                "cmd": "MoveJ",
                "target": f"[{self.fmt_joints(wp.target)}]",
                "speed": f"v{int(wp.speed)}",
                "zone": f"z{int(wp.blend)}" if wp.blend > 0 else "fine",
            }
        elif wp.type == _core.MoveType.LINEAR:
            return {
                "cmd": "MoveL",
                "target": f"[{self.fmt_pose(wp.target, order='xyz')}]",
                "speed": f"v{int(wp.speed)}",
                "zone": f"z{int(wp.blend)}" if wp.blend > 0 else "fine",
            }
        return {"cmd": "! UNKNOWN", "target": "", "speed": "", "zone": ""}

    def _get_template(self) -> str:
        return """MODULE {{ meta.program_name|default('OROLPModule') }}
    ! Generated by OpenRoboOLP v{{ meta.version|default('0.1.0') }}

    PROC main()
        {% for wp in waypoints %}
        {{ wp.cmd }} {{ wp.target }}, {{ wp.speed }}, {{ wp.zone }};
        {% endfor %}
    ENDPROC
ENDMODULE
"""
