from .base import BasePostProcessor, PostConfig
from .. import _core


class KUKAKRC4PostProcessor(BasePostProcessor):
    brand = "kuka"
    controller = "krc4"

    def __init__(self):
        super().__init__(PostConfig(precision=3, speed_unit="%", comment_char=";"))

    def _convert_wp(self, wp):
        if wp.type == _core.MoveType.JOINT:
            return {
                "cmd": "PTP",
                "target": self.fmt_joints(wp.target),
                "speed": self.fmt_speed(wp.speed, wp.type),
                "blend": "C_DIS" if wp.blend > 0 else "",
            }
        elif wp.type == _core.MoveType.LINEAR:
            return {
                "cmd": "LIN",
                "target": self.fmt_pose(wp.target, order="zyx"),
                "speed": self.fmt_speed(wp.speed, wp.type),
                "blend": "C_DIS" if wp.blend > 0 else "",
            }
        return {"cmd": "; UNKNOWN", "target": "", "speed": "", "blend": ""}

    def _get_template(self) -> str:
        return """&ACCESS RVP
&REL 1
DEF {{ meta.program_name|default('OROLP_PROG') }}()
    ; Generated by OpenRoboOLP v{{ meta.version|default('0.1.0') }}
    BAS(#INITMOV, 0)

    {% for wp in waypoints %}
    {{ wp.cmd }} {% if wp.cmd == 'PTP' %}{{ wp.target }}{% else %}{{ wp.target }}{% endif %} {{ wp.blend }}
    {% endfor %}

    END
"""
